var clients = [
    {
        "PersonType": "Client",
        "Id": 95896,
        "SavedProfileId": "Client:95896",
        "Gender": "M",
        "Title": "Mr.",
        "FirstName": "Pritam",
        "MiddleName": "",
        "LastName": "Samantaray",
        "Phone": "00001111010",
        "Email": null,
        "DateOfBirth": "1993-05-17T00:00:00",
        "IsAgentActive": null,
        "PrimaryAgentName": "System Kensingtontours",
        "AdminOfficeName": "",
        "DisplayName": "Pritam Samantaray",
        "IsCorporateClient": false,
        "UpcomingTrip": null,
        "LastTrip": null
    },
    {
        "PersonType": "Client",
        "Id": 95900,
        "SavedProfileId": "Client:95900",
        "Gender": "M",
        "Title": "Mr.",
        "FirstName": "Roberto",
        "MiddleName": "",
        "LastName": "Cavilli",
        "Phone": "8817836876233",
        "Email": null,
        "DateOfBirth": "1989-02-10T00:00:00",
        "IsAgentActive": null,
        "PrimaryAgentName": "Agent1 Ktair",
        "AdminOfficeName": "",
        "DisplayName": "Roberto Cavilli",
        "IsCorporateClient": false,
        "UpcomingTrip": null,
        "LastTrip": null
    },
    {
        "PersonType": "Client",
        "Id": 95702,
        "SavedProfileId": "Client:95702",
        "Gender": "M",
        "Title": "Mr.",
        "FirstName": "Vivek",
        "MiddleName": "",
        "LastName": "Nikam",
        "Phone": "88617658157653",
        "Email": "vivek.nikam@galepartners.com",
        "DateOfBirth": "1992-07-29T00:00:00",
        "IsAgentActive": null,
        "PrimaryAgentName": "Agent1 Ktair",
        "AdminOfficeName": "",
        "DisplayName": "Vivek Nikam",
        "IsCorporateClient": false,
        "UpcomingTrip": null,
        "LastTrip": null
    }];